
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#DuckDNS/Let'sEncrypt
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
